version: '3'
services:
  postgres:
    image: 'postgres:14.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./../volumes/postgres-data:/var/lib/postgresql/data